"""
Shared path constants for the sre_test platform.
Used by both SIL and HIL components.
"""

from pathlib import Path

# This file is at: dev/test/sre_test/core/path.py
_core_dir = Path(__file__).parent        # dev/test/sre_test/core/
_sre_test_dir = _core_dir.parent         # dev/test/sre_test/
_test_dir = _sre_test_dir.parent         # dev/test/
_dev_dir = _test_dir.parent              # dev/
_root_dir = _dev_dir.parent              # VCU root/

ROOT = _root_dir
DEV = _dev_dir
INC = _root_dir / 'inc'
TEST = _test_dir
SRE_TEST = _sre_test_dir
CORE = _core_dir

# Struct definitions are generated by SIL (sre sil extract) and shared across backends
CONFIG = _sre_test_dir / 'config'
STRUCT_MEMBERS = CONFIG / 'vcu_structs_map.json'

# Unified test directory (backend-agnostic tests live here)
SHARED_TESTS = _sre_test_dir / 'tests'
